name: test secret

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  #schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test var
      run: |
        echo "12455" > t.txt
        echo "sec=$(cat t.txt)" >> "$GITHUB_ENV"
    - name: test echo
      run: |
        echo $sec
    - name: Checkout
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'Test'
        value: ${{ env.sec }}
        repository: cute-rui/E5RENEW
        token: ${{ secrets.GH_TOKEN }}
    - name: echo
      run: | 
        echo ${#${{ secrets.Test }}}
