name: test secret

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  #schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
  watch:
    types: [started]
   
jobs:
  test:
    outputs:
        test-result: ${{ steps.set_outputs.outputs.test-result }}
    runs-on: ubuntu-latest
    steps:
    - name: set outputs
      id: set_outputs
      run: |
        echo "::set-output name=test-result::'daindae'"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test echo
      run: |
        echo "::set-env name=TEST_RESULT::${{ needs.test.outputs.test-result }}"
        echo $TEST_RESULT
    - name: Checkout
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'Test'
        value: 'Lorem ipsun dolor simit'
        repository: cute-rui/E5RENEW
        token: ${{ secrets.GH_TOKEN }}
    - name: echo
      run: | 
        echo ${{ secrets.Test }}
